import type { RecipeInput } from "../src/features/recipes/schemas";

export type SeedUser = { key: string; name: string; email: string };
export type SeedRecipe = RecipeInput & { slug: string; author: string; imageUrl: string };

export const SEED_USERS: SeedUser[] = [
  { key: "maya", name: "Maya Patel", email: "maya@example.com" },
  { key: "sam", name: "Sam Rivera", email: "sam@example.com" },
  { key: "jo", name: "Jo Chen", email: "jo@example.com" },
];

const ing = (quantity: string, unit: string, name: string, note = "") => ({
  quantity,
  unit,
  name,
  note,
});
const steps = (...texts: string[]) => texts.map((text) => ({ text }));

export const SEED_RECIPES: SeedRecipe[] = [
  {
    slug: "weeknight-red-lentil-dal",
    author: "maya",
    imageUrl: "/seed/red-lentil-dal.webp",
    title: "Weeknight Red Lentil Dal",
    description:
      "Creamy red lentils simmered with turmeric, cumin, and garlic. Ready in about 35 minutes.",
    prepMinutes: 10,
    cookMinutes: 25,
    servings: 4,
    difficulty: "EASY",
    cuisine: "Indian",
    tags: ["vegan", "gluten-free"],
    ingredients: [
      ing("1 1/2", "cups", "red lentils", "rinsed"),
      ing("1", "", "onion", "diced"),
      ing("3", "cloves", "garlic", "minced"),
      ing("1", "tbsp", "ginger", "grated"),
      ing("1", "tsp", "ground turmeric"),
      ing("1", "tsp", "cumin seeds"),
      ing("1", "can", "coconut milk"),
      ing("3", "cups", "water"),
      ing("2", "tbsp", "vegetable oil"),
      ing("", "", "salt", "to taste"),
    ],
    steps: steps(
      "Heat the oil in a pot over medium heat. Add the cumin seeds and cook until fragrant, about 30 seconds.",
      "Add the onion and cook until soft, 5 minutes. Stir in the garlic, ginger, and turmeric for 1 minute.",
      "Add the lentils, coconut milk, and water. Bring to a simmer and cook, stirring often, until the lentils break down, about 20 minutes.",
      "Season with salt and serve with rice or flatbread.",
    ),
  },
  {
    slug: "lemony-chickpea-salad",
    author: "maya",
    imageUrl: "/seed/lemony-chickpea-salad.webp",
    title: "Lemony Chickpea Salad",
    description: "A bright, crunchy salad that keeps well for lunches all week.",
    prepMinutes: 15,
    cookMinutes: 0,
    servings: 4,
    difficulty: "EASY",
    cuisine: "Mediterranean",
    tags: ["vegan", "quick", "gluten-free"],
    ingredients: [
      ing("2", "cans", "chickpeas", "drained and rinsed"),
      ing("1", "", "cucumber", "diced"),
      ing("1", "pint", "cherry tomatoes", "halved"),
      ing("1/2", "", "red onion", "finely diced"),
      ing("1/4", "cup", "parsley", "chopped"),
      ing("1", "", "lemon", "juiced"),
      ing("3", "tbsp", "olive oil"),
      ing("", "", "salt"),
      ing("", "", "black pepper"),
    ],
    steps: steps(
      "Whisk the lemon juice, olive oil, salt, and pepper in a large bowl.",
      "Add the chickpeas, cucumber, tomatoes, onion, and parsley. Toss well.",
      "Rest for 10 minutes so the flavors come together, then taste and adjust the seasoning.",
    ),
  },
  {
    slug: "classic-buttermilk-pancakes",
    author: "sam",
    imageUrl: "/seed/buttermilk-pancakes.webp",
    title: "Classic Buttermilk Pancakes",
    description: "Tall, fluffy pancakes with crisp edges. The batter comes together in one bowl.",
    prepMinutes: 10,
    cookMinutes: 20,
    servings: 4,
    difficulty: "EASY",
    cuisine: "American",
    tags: ["vegetarian", "breakfast"],
    ingredients: [
      ing("2", "cups", "all-purpose flour"),
      ing("2", "tbsp", "sugar"),
      ing("2", "tsp", "baking powder"),
      ing("1/2", "tsp", "baking soda"),
      ing("1/2", "tsp", "salt"),
      ing("2", "cups", "buttermilk"),
      ing("2", "", "eggs"),
      ing("3", "tbsp", "butter", "melted, plus more for the pan"),
    ],
    steps: steps(
      "Whisk the flour, sugar, baking powder, baking soda, and salt in a large bowl.",
      "In another bowl, whisk the buttermilk, eggs, and melted butter. Pour into the dry ingredients and stir until just combined. A few lumps are fine.",
      "Heat a buttered skillet over medium heat. Pour 1/4 cup of batter per pancake and cook until bubbles form, about 2 minutes.",
      "Flip and cook until golden, 1 to 2 minutes more. Serve warm.",
    ),
  },
  {
    slug: "garlic-butter-shrimp-pasta",
    author: "sam",
    imageUrl: "/seed/garlic-butter-shrimp-pasta.webp",
    title: "Garlic Butter Shrimp Pasta",
    description: "Linguine tossed with garlicky butter, lemon, and quick-cooked shrimp.",
    prepMinutes: 10,
    cookMinutes: 15,
    servings: 4,
    difficulty: "MEDIUM",
    cuisine: "Italian",
    tags: ["quick"],
    ingredients: [
      ing("12", "oz", "linguine"),
      ing("1", "lb", "shrimp", "peeled and deveined"),
      ing("4", "tbsp", "butter"),
      ing("5", "cloves", "garlic", "thinly sliced"),
      ing("1/2", "tsp", "red pepper flakes"),
      ing("1", "", "lemon", "zested and juiced"),
      ing("1/4", "cup", "parsley", "chopped"),
      ing("", "", "salt"),
    ],
    steps: steps(
      "Cook the linguine in salted boiling water until al dente. Save 1 cup of the pasta water, then drain.",
      "Melt the butter in a large skillet over medium heat. Add the garlic and pepper flakes and cook for 1 minute.",
      "Add the shrimp and cook until pink, about 2 minutes per side.",
      "Add the pasta, lemon zest and juice, and a splash of pasta water. Toss until glossy, then finish with parsley.",
    ),
  },
  {
    slug: "black-bean-tacos",
    author: "jo",
    imageUrl: "/seed/black-bean-tacos.webp",
    title: "Smoky Black Bean Tacos",
    description: "Crispy-edged black beans with smoked paprika, quick pickled onions, and lime.",
    prepMinutes: 10,
    cookMinutes: 10,
    servings: 3,
    difficulty: "EASY",
    cuisine: "Mexican",
    tags: ["vegetarian", "quick"],
    ingredients: [
      ing("2", "cans", "black beans", "drained"),
      ing("1", "tsp", "smoked paprika"),
      ing("1", "tsp", "ground cumin"),
      ing("6", "", "corn tortillas"),
      ing("1/2", "", "red onion", "thinly sliced"),
      ing("2", "", "limes"),
      ing("1/2", "cup", "cotija cheese", "crumbled"),
      ing("", "", "cilantro", "for serving"),
      ing("1", "tbsp", "olive oil"),
    ],
    steps: steps(
      "Toss the onion with the juice of 1 lime and a pinch of salt. Set aside to pickle.",
      "Heat the oil in a skillet. Add the beans, paprika, and cumin, and cook, pressing some beans flat, until crisp in spots, about 6 minutes.",
      "Warm the tortillas in a dry pan.",
      "Fill the tortillas with beans, pickled onion, cheese, and cilantro. Serve with lime wedges.",
    ),
  },
  {
    slug: "sheet-pan-chicken-and-vegetables",
    author: "jo",
    imageUrl: "/seed/sheet-pan-chicken.webp",
    title: "Sheet Pan Chicken and Vegetables",
    description: "Juicy chicken thighs roasted on one pan with potatoes, carrots, and red onion.",
    prepMinutes: 15,
    cookMinutes: 40,
    servings: 4,
    difficulty: "EASY",
    cuisine: "American",
    tags: ["gluten-free"],
    ingredients: [
      ing("6", "", "chicken thighs", "bone-in, skin-on"),
      ing("1", "lb", "baby potatoes", "halved"),
      ing("4", "", "carrots", "cut into chunks"),
      ing("1", "", "red onion", "cut into wedges"),
      ing("3", "tbsp", "olive oil"),
      ing("1", "tsp", "dried thyme"),
      ing("1", "tsp", "garlic powder"),
      ing("", "", "salt"),
      ing("", "", "black pepper"),
    ],
    steps: steps(
      "Heat the oven to 425°F (220°C).",
      "Toss the potatoes, carrots, and onion with half the oil, salt, and pepper on a sheet pan.",
      "Rub the chicken with the rest of the oil, thyme, garlic powder, salt, and pepper. Nestle it skin side up among the vegetables.",
      "Roast until the chicken reaches 175°F (80°C) and the skin is crisp, 35 to 40 minutes.",
    ),
  },
  {
    slug: "egg-fried-rice",
    author: "jo",
    imageUrl: "/seed/egg-fried-rice.webp",
    title: "Egg Fried Rice",
    description:
      "The best use for leftover rice: fluffy eggs, scallions, and a splash of soy sauce.",
    prepMinutes: 5,
    cookMinutes: 10,
    servings: 2,
    difficulty: "EASY",
    cuisine: "Chinese",
    tags: ["vegetarian", "quick"],
    ingredients: [
      ing("3", "cups", "cooked rice", "cold, day old"),
      ing("3", "", "eggs", "beaten"),
      ing("4", "", "scallions", "sliced"),
      ing("1/2", "cup", "frozen peas"),
      ing("2", "tbsp", "soy sauce"),
      ing("1", "tsp", "sesame oil"),
      ing("2", "tbsp", "vegetable oil"),
    ],
    steps: steps(
      "Heat 1 tablespoon of oil in a wok over high heat. Scramble the eggs until just set, then move them to a plate.",
      "Add the rest of the oil and the rice. Stir-fry, breaking up clumps, until hot and starting to crisp, 3 to 4 minutes.",
      "Add the peas and most of the scallions and cook 1 minute.",
      "Return the eggs, add the soy sauce and sesame oil, and toss. Top with the remaining scallions.",
    ),
  },
  {
    slug: "tomato-basil-soup",
    author: "maya",
    imageUrl: "/seed/tomato-basil-soup.webp",
    title: "Roasted Tomato Basil Soup",
    description: "Roasting the tomatoes first gives this soup a deep, sweet flavor.",
    prepMinutes: 15,
    cookMinutes: 45,
    servings: 4,
    difficulty: "MEDIUM",
    cuisine: "Italian",
    tags: ["vegan", "gluten-free"],
    ingredients: [
      ing("3", "lb", "tomatoes", "halved"),
      ing("1", "", "onion", "quartered"),
      ing("6", "cloves", "garlic"),
      ing("3", "tbsp", "olive oil"),
      ing("2", "cups", "vegetable broth"),
      ing("1", "cup", "basil leaves"),
      ing("", "", "salt"),
      ing("", "", "black pepper"),
    ],
    steps: steps(
      "Heat the oven to 400°F (200°C). Toss the tomatoes, onion, and garlic with oil, salt, and pepper on a sheet pan.",
      "Roast until soft and browned at the edges, about 35 minutes.",
      "Transfer to a pot with the broth and simmer 10 minutes.",
      "Add the basil and blend until smooth. Taste and adjust the seasoning.",
    ),
  },
];
